### ISSUE TITLE
Optional adx feature support?

### ISSUE THREAD

**Issue by qy3u** [filecoin-project/blstrs#16]
The blst crate support an optional adx feature:
https://github.com/supranational/blst/blob/7f6aa706670aa090f0cb69850bc1c388b459c438/bindings/rust/build.rs#L85

The CPU of our build machines are support adx instruction but our target machine are not.

The current code of blstrs does not support an optional adx feature. It means that even we remove the adx optimize [here](https://github.com/filecoin-project/filecoin-ffi/blob/0c50dfbaa64c6187d65e63e19aea751a981ac931/rust/rustc-target-features-optimized.json#L2) and there is no '+adx' arg in rust's target feature, adx instruction will still be enabled.

So,may be a optional adx feature support here?

**Comment by dignifiedquire** [comment]
Yes we should support all available features that `blst` exposes

**Comment by dignifiedquire** [comment]
We now have the `portable` feature, which I believe should help with this

**Comment by qy3u** [comment]
Thanks!
