### ISSUE TITLE
Add x86 support for blstrs

### ISSUE THREAD

**Issue by spylogsster** [filecoin-project/blstrs#29]
We are working on Filecoin integration to the Brave Wallet and we need support for x86 versions for blstrs

**Comment by dignifiedquire** [comment]
I am afraid that will not be possible, given that the underlying library `blst` does not support 32bit architectures. See https://github.com/supranational/blst#platform-and-language-compatibility.

What you can do is use https://docs.rs/bls12_381/ which is API compatible, and is being used as an alternative backend in https://github.com/filecoin-project/bls-signatures, which works well for different enviroments.

**Comment by spylogsster** [comment]
Thank you for the response, that library says that  **This implementation has not been reviewed or audited. Use at your own risk**. are you sure we can use it @dignifiedquire  ?

**Comment by dot-asm** [comment]
> `blst` does not support 32bit architectures.

While it's true that 32-bit platforms are not explicitly listed, blst does run on plethora or unlisted platforms. There even were reports from Rust on wasm users.

**Comment by dignifiedquire** [comment]
@dot-asm alright, I guess I'll try and see what I can get working

**Comment by dignifiedquire** [comment]
Looks like we might be able to support 32bit after all: https://github.com/filecoin-project/blstrs/pull/30
